# -*- coding: utf-8 -*-
"""RLA1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11iVjT7lEQemyS2FyUK7AqUlJ8871hJGG

#**CS 4391/5391 - Reinforcement Learning**
#**Homework 1**

**Task 1: Designing the Bandit**

**1.1 Distribution Visualization**
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.special as sps

# Choose 3 Gamma distributions (shape, scale)
arms = [
    ("Arm 1", 0.7, 2.0),
    ("Arm 2", 1.5, 2.0),
    ("Arm 3", 2.0, 2.0),
    ("Arm 4", 5.0, 1.5),
    ("Arm 5", 7.0, 1.5),
]
means = []

for name, shape, scale in arms:
    # 1) Sample 1000 rewards
    samples = np.random.gamma(shape, scale, 1000)

    # 2) Create the histogram
    count, bins, ignored = plt.hist(samples, 50, density=True, alpha=0.6)

    # 3) Calculate the theoretical PDF line
    y = bins**(shape - 1) * (np.exp(-bins / scale) / (sps.gamma(shape) * scale**shape))

    # 4) Plotting
    plt.plot(bins, y, linewidth=2, color='r', label='Theoretical PDF')
    plt.title(f"{name}: shape={shape}, scale={scale}, mean={shape*scale:.2f}")
    plt.xlabel("Reward")
    plt.ylabel("Density")
    plt.legend()
    plt.show()

"""**1.2 Statistical Analysis**

Mean rewards (mu = shape * scale):

Arm 1: 1.40

Arm 2: 3.00

Arm 3: 4.00

Arm 4: 7.50

Arm 5: 10.50

**Optimal arm: Arm 5** (highest mean = 10.50)

**Task 2: Training the Agent**

**2.1 Average Reward Analysis**
"""

np.random.seed(0)

# Arms from Task 1 (name, shape, scale)
arms = [
    ("Arm 1", 0.7, 2.0),
    ("Arm 2", 1.5, 2.0),
    ("Arm 3", 2.0, 2.0),
    ("Arm 4", 5.0, 1.5),
    ("Arm 5", 7.0, 1.5),
]

shapes = np.array([a[1] for a in arms], dtype=float)
scales = np.array([a[2] for a in arms], dtype=float)
n_arms = len(arms)

# Parameters
max_steps = 1000
window = 100
tol = 1e-3
eps_list = [0.01, 0.1, 0.3]

def run_eps_greedy_avg(eps):
    Q = np.zeros(n_arms)
    N = np.zeros(n_arms)
    avg_rewards = []
    total_reward = 0.0

    for t in range(1, max_steps + 1):
        # pick action
        if np.random.rand() < eps:
            a = np.random.randint(n_arms)
        else:
            a = np.argmax(Q)

        # get reward
        r = np.random.gamma(shapes[a], scales[a])

        # update
        N[a] += 1
        Q[a] = Q[a] + (r - Q[a]) / N[a]

        total_reward += r
        avg_rewards.append(total_reward / t)

        # early stop if average reward is flat for last 100 games
        if t > window:
            recent = avg_rewards[-window:]
            if (max(recent) - min(recent)) < tol:
                break

    return np.array(avg_rewards)

def run_ucb_avg():
    Q = np.zeros(n_arms)
    N = np.zeros(n_arms)
    avg_rewards = []
    total_reward = 0.0

    for t in range(1, max_steps + 1):
        # pick action
        if 0 in N:
            a = int(np.where(N == 0)[0][0])  # try each arm once
        else:
            ucb = Q + 2.0 * np.sqrt(np.log(t) / N)
            a = int(np.argmax(ucb))

        # get reward
        r = np.random.gamma(shapes[a], scales[a])

        # update
        N[a] += 1
        Q[a] = Q[a] + (r - Q[a]) / N[a]

        total_reward += r
        avg_rewards.append(total_reward / t)

        # early stop
        if t > window:
            recent = avg_rewards[-window:]
            if (max(recent) - min(recent)) < tol:
                break

    return np.array(avg_rewards)

# Run experiments
results = {}
results["UCB"] = run_ucb_avg()

for eps in eps_list:
    results[f"eps={eps}"] = run_eps_greedy_avg(eps)

# Plot average reward
plt.figure(figsize=(9, 5))
for label, curve in results.items():
    plt.plot(np.arange(1, len(curve) + 1), curve, linewidth=2, label=label)

plt.xlabel("Game time (t)")
plt.ylabel("Average reward")
plt.title("Task 2.1: Average Reward vs Time")
plt.legend()
plt.grid(True)
plt.show()

"""UCB (blue) reaches a high average reward quickly and stays the highest overall, showing it learns the best arm fast. ε-greedy with ε=0.1 (green) also performs well early but stays slightly below UCB. ε=0.3 (red) levels off lower because it keeps exploring too much, while ε=0.01 (orange) improves slowly at first but steadily increases as it exploits more after learning.

**2.2 Optimal Action Selection**
"""

np.random.seed(0)

# Arms from Task 1 (name, shape, scale)
arms = [
    ("Arm 1", 0.7, 2.0),
    ("Arm 2", 1.5, 2.0),
    ("Arm 3", 2.0, 2.0),
    ("Arm 4", 5.0, 1.5),
    ("Arm 5", 7.0, 1.5),
]

shapes = np.array([a[1] for a in arms], dtype=float)
scales = np.array([a[2] for a in arms], dtype=float)
n_arms = len(arms)

# Find true optimal arm (highest mean)
true_means = shapes * scales
best_arm = int(np.argmax(true_means))
print("Best arm:", arms[best_arm][0], " mean =", true_means[best_arm])

# Parameters
max_steps = 1000
window = 100
tol = 1e-3
eps_list = [0.01, 0.1, 0.3]

def run_eps_greedy_opt(eps):
    Q = np.zeros(n_arms)
    N = np.zeros(n_arms)
    pct_opt = []
    opt_count = 0

    for t in range(1, max_steps + 1):
        # pick action
        if np.random.rand() < eps:
            a = np.random.randint(n_arms)
        else:
            a = np.argmax(Q)

        # reward
        r = np.random.gamma(shapes[a], scales[a])

        # update
        N[a] += 1
        Q[a] = Q[a] + (r - Q[a]) / N[a]

        # track optimal action %
        if a == best_arm:
            opt_count += 1
        pct_opt.append(100.0 * opt_count / t)

        # early stop if % optimal is flat for last 100 games
        if t > window:
            recent = pct_opt[-window:]
            if (max(recent) - min(recent)) < tol:
                break

    return np.array(pct_opt)

def run_ucb_opt():
    Q = np.zeros(n_arms)
    N = np.zeros(n_arms)
    pct_opt = []
    opt_count = 0

    for t in range(1, max_steps + 1):
        # pick action
        if 0 in N:
            a = int(np.where(N == 0)[0][0])
        else:
            ucb = Q + 2.0 * np.sqrt(np.log(t) / N)
            a = int(np.argmax(ucb))

        # reward
        r = np.random.gamma(shapes[a], scales[a])

        # update
        N[a] += 1
        Q[a] = Q[a] + (r - Q[a]) / N[a]

        # track optimal action %
        if a == best_arm:
            opt_count += 1
        pct_opt.append(100.0 * opt_count / t)

        # early stop
        if t > window:
            recent = pct_opt[-window:]
            if (max(recent) - min(recent)) < tol:
                break

    return np.array(pct_opt)

# Run experiments
results = {}
results["UCB"] = run_ucb_opt()

for eps in eps_list:
    results[f"eps={eps}"] = run_eps_greedy_opt(eps)

# Plot % optimal actions
plt.figure(figsize=(9, 5))
for label, curve in results.items():
    plt.plot(np.arange(1, len(curve) + 1), curve, linewidth=2, label=label)

plt.xlabel("Game time (t)")
plt.ylabel("% Optimal actions")
plt.title("Task 2.2: % Optimal Actions vs Time")
plt.legend()
plt.grid(True)
plt.show()

"""UCB (blue) quickly increases the percentage of optimal actions and finishes the highest (close to 100%), meaning it learns the best arm and keeps choosing it most of the time. ε=0.1 (green) also reaches a high optimal-action rate (around 90%) but stays lower because it continues exploring. ε=0.3 (red) ends much lower (around 70–75%) since heavy exploration causes many non-optimal choices."""